### ISSUE TITLE
建议支持一下冰蝎4的webshell免杀

### ISSUE THREAD

**Issue by Nyx2022** [cseroad/Webshell_Generate#10]

**Comment by cseroad** [comment]
好主意

**Comment by cseroad** [comment]
冰蝎4默认不也是使用冰蝎3的加密方式吗

**Comment by Nyx2022** [comment]
> 冰蝎4默认不也是使用冰蝎3的加密方式吗

不一样，冰蝎4里面多了个magic和自定义加解密算法的设定。如果能支持我提供一个webshell，然后工具直接对其进行免杀处理之后返回免杀后的结果也行，现在这种感觉无法自定义里面的一些加解密函数

**Comment by cseroad** [comment]
提供一个webshell依然要遵循冰蝎4的加密协议，比如default_aes，只能在这个上面进行处理免杀。然后可以兼容asp、php、jsp各个服务端
