### ISSUE TITLE
aspx哥斯拉的密码是啥

### ISSUE THREAD

**Issue by ifacker** [cseroad/Webshell_Generate#13]
aspx哥斯拉的密码是啥？设置的密码对应的是pass还是key？
<img width="977" alt="image" src="https://github.com/cseroad/Webshell_Generate/assets/26481367/468e6eb2-cb86-48df-bfa6-5a4b36e92d5a">

**Comment by cseroad** [comment]
可以将pass和key设置为相同的值

**Comment by keyboardancer** [comment]
> 可以将pass和key设置为相同的值

师傅，好像不行呀，生成时只能输密码。我在链接的时候，pass和key都设置成了一个值，还是连不上呢，这是咋回事？

**Comment by cseroad** [comment]
师傅确定一下连接的模式是否是AES_RAW。如果依然连接不上，试一试哥斯拉默认生成，验证是否正常连接

**Comment by keyboardancer** [comment]
> 师傅确定一下连接的模式是否是AES_RAW。如果依然连接不上，试一试哥斯拉默认生成，验证是否正常连接

我测了一下默认生成的也连接不了，可能是环境有问题
