### ISSUE TITLE
生成php的antsword_base64的webshell，用蚁剑无法连接，返回空，应该怎么处理？ 

### ISSUE THREAD

**Issue by y54king** [cseroad/Webshell_Generate#16]
生成php的antsword_base64的webshell，用蚁剑无法连接，返回空，应该怎么处理？

**Comment by cseroad** [comment]
师傅设置蚁剑编码器选择的是base64吗

**Comment by y54king** [comment]
是的，base64

**Comment by cseroad** [comment]
师傅php版本是多少

**Comment by y54king** [comment]
测试环境使用的phpstudy，靶场是upload-lab，php版本7.3.4nts

**Comment by cseroad** [comment]
据我所知，assert函数在php7版本以后不能执行代码了

**Comment by y54king** [comment]
谢谢师傅指教，确实是php版本问题，使用php5就可以了。
