### ISSUE TITLE
PS C:\Users\jwf\Desktop\常用> java.exe -jar .\Webshell_Generate-1.1.jar 错误: 找不到或无法加载主类 sample.Main 原因: java.lang.NoClassDefFoundError: javafx/application/Application

### ISSUE THREAD

**Issue by ruisika** [cseroad/Webshell_Generate#2]

**Comment by ruisika** [comment]
这是什么原因啊：>

**Comment by cseroad** [comment]
使用jdk8环境运行

**Comment by ruisika** [comment]
C:\Users\jwf>"C:\Program Files\Java\jdk1.8.0_341\bin\java.exe" C:\Users\jwf\Desktop\Webshell_Generate-1.1.jar
错误: 找不到或无法加载主类 C:\Users\jwf\Desktop\Webshell_Generate-1.1.jar

**Comment by cseroad** [comment]
java -jar  Webshell_Generate-1.1.jar

**Comment by p1ziYu** [comment]
我觉得他可能是因为Javafx的环境设置错误了，因为我现在也卡这了，实在不知道JavaFX该怎么弄了。。。

**Comment by cseroad** [comment]
师傅用jdk8运行不行吗

**Comment by p1ziYu** [comment]
> 师傅用jdk8运行不行吗

我等等试试去

**Comment by p1ziYu** [comment]
jdk8运行是正常的，查了查应该是jdk17不带javafx了，所以需要自己去配置
