### ISSUE TITLE
jsp无法连接

### ISSUE THREAD

**Issue by admin-set** [cseroad/Webshell_Generate#3]
![image](https://user-images.githubusercontent.com/63496176/190904120-e6063bf5-adb9-460c-a970-6a03c642b5b6.png)
jsp-webshell  无法连接、也访问不到
修改本地文件名称为admin.jsp.txt 可以访问到
![image](https://user-images.githubusercontent.com/63496176/190904217-47e3cee8-9be0-402b-9226-84ca2196e7d2.png)

**Comment by cseroad** [comment]
jsp_webshell 访问为404，依然可以连接
