### ISSUE TITLE
jsp_godzill_java_aes_raw 生成的webshell无法连接

### ISSUE THREAD

**Issue by axingde** [cseroad/Webshell_Generate#4]
生成
![image](https://user-images.githubusercontent.com/65204372/194744720-83409739-184c-4113-b4f9-d739d14b57cb.png)

访问空白：
![image](https://user-images.githubusercontent.com/65204372/194744737-2374c488-270c-4042-8b81-ab8c61eccab6.png)

哥斯拉连接失败
![image](https://user-images.githubusercontent.com/65204372/194744756-4aeb918d-c1ad-43aa-a994-21c3281a36c1.png)

**Comment by axingde** [comment]
![image](https://user-images.githubusercontent.com/65204372/194744896-269a3e4b-ed96-45dc-8562-6705852fc846.png)

**Comment by cseroad** [comment]
java填写秘钥，而不是密码

**Comment by axingde** [comment]
连接填写配置时密码要填写什么

**Comment by axingde** [comment]
了解，多谢师傅，测试连接成功了
