### ISSUE TITLE
无法生成特殊字符密码

### ISSUE THREAD

**Issue by Evi10x01** [cseroad/Webshell_Generate#7]
想生成带特殊字符的密码，输入包含特殊字符的密码后，特殊字符的内容自动替换成空格。
例：输入"qaz123!@#"的密码，GUI上仅显示"qaz123   "的密码，特殊字符内容自动替换成空格，无法生成包含特殊符号密码的webshell

**Comment by cseroad** [comment]
<img width="1212" alt="image" src="https://github.com/cseroad/Webshell_Generate/assets/59865739/d9febb07-4396-431f-91a9-8faf9603fd36">

对输入的特殊字符进行过滤是代码里特意加上的，大概率是当时写的时候考虑了通用性。经过刚才的测试，各个webshell连接器均以支持特殊字符，可以考虑在下个版本去除该正则处理。
